// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlhYhQtms4Sez_gb6ndIdt9PJFUUbUrFY',
    appId: '1:34635033582:android:8db589874a709ed45dbcff',
    messagingSenderId: '34635033582',
    projectId: 'zenn-gcp-flutter',
    storageBucket: 'zenn-gcp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDIo6fcyxfJlJz2b28BsTz1wYLqlqQPaQ',
    appId: '1:34635033582:ios:ea85edb163bcc22c5dbcff',
    messagingSenderId: '34635033582',
    projectId: 'zenn-gcp-flutter',
    storageBucket: 'zenn-gcp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDIo6fcyxfJlJz2b28BsTz1wYLqlqQPaQ',
    appId: '1:34635033582:ios:ea85edb163bcc22c5dbcff',
    messagingSenderId: '34635033582',
    projectId: 'zenn-gcp-flutter',
    storageBucket: 'zenn-gcp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );
}
